Script started on Tue 06 Nov 2012 11:35:13 AM PST
[?1034hbash-4.1$ valgrind --leak-check=full \list3 foo bar baz qux
==12485== Memcheck, a memory error detector
==12485== Copyright (C) 2002-2010, and GNU GPL'd, by Julian Seward et al.
==12485== Using Valgrind-3.6.0 and LibVEX; rerun with -h for copyright info
==12485== Command: list3 foo bar baz qux
==12485== 
0x4c23180->node {word=0x7ff0005fd->[qux], link=0x4c23130}
0x4c23130->node {word=0x7ff0005f9->[baz], link=0x4c230e0}
0x4c230e0->node {word=0x7ff0005f5->[bar], link=0x4c23090}
0x4c23090->node {word=0x7ff0005f1->[foo], link=0x4c23040}
==12485== 
==12485== HEAP SUMMARY:
==12485==     in use at exit: 80 bytes in 5 blocks
==12485==   total heap usage: 5 allocs, 0 frees, 80 bytes allocated
==12485== 
==12485== 80 (16 direct, 64 indirect) bytes in 1 blocks are definitely lost in loss record 2 of 2
==12485==    at 0x4A05FDE: malloc (vg_replace_malloc.c:236)
==12485==    by 0x4005BE: main (list3.c:16)
==12485== 
==12485== LEAK SUMMARY:
==12485==    definitely lost: 16 bytes in 1 blocks
==12485==    indirectly lost: 64 bytes in 4 blocks
==12485==      possibly lost: 0 bytes in 0 blocks
==12485==    still reachable: 0 bytes in 0 blocks
==12485==         suppressed: 0 bytes in 0 blocks
==12485== 
==12485== For counts of detected and suppressed errors, rerun with: -v
==12485== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 6 from 6)
bash-4.1$ exit
exit

Script done on Tue 06 Nov 2012 11:35:43 AM PST
