Script started on Tue 06 Nov 2012 10:34:13 AM PST
[?1034hbash-4.1$ mk list2.c
+ for CSOURCE in '$*'
+ cid + list2.c
+ checksource list2.c
++ echo list2.c
++ sed 's/\.c$//'
+ EXECBIN=list2
+ gcc -g -O0 -Wall -Wextra -std=gnu99 list2.c -o list2 -lm
list2.c: In function ‘main’:
list2.c:13: warning: unused parameter ‘argc’
bash-4.1$ valgrind list2 foo bar
==5432== Memcheck, a memory error detector
==5432== Copyright (C) 2002-2010, and GNU GPL'd, by Julian Seward et al.
==5432== Using Valgrind-3.6.0 and LibVEX; rerun with -h for copyright info
==5432== Command: list2 foo bar
==5432== 
==5432== Invalid write of size 8
==5432==    at 0x4005FA: main (list2.c:19)
==5432==  Address 0x4c23048 is 0 bytes after a block of size 8 alloc'd
==5432==    at 0x4A05FDE: malloc (vg_replace_malloc.c:236)
==5432==    by 0x4005B6: main (list2.c:16)
==5432== 
==5432== Invalid read of size 8
==5432==    at 0x40065C: main (list2.c:22)
==5432==  Address 0x4c23188 is 0 bytes after a block of size 8 alloc'd
==5432==    at 0x4A05FDE: malloc (vg_replace_malloc.c:236)
==5432==    by 0x4005B6: main (list2.c:16)
==5432== 
==5432== Invalid read of size 8
==5432==    at 0x40061E: main (list2.c:23)
==5432==  Address 0x4c23188 is 0 bytes after a block of size 8 alloc'd
==5432==    at 0x4A05FDE: malloc (vg_replace_malloc.c:236)
==5432==    by 0x4005B6: main (list2.c:16)
==5432== 
0x4c23180->node {word=0x7ff0005d5->[HOSTNAME=unix2.ic.ucsc.edu], link=0x4c23130}
==5432== Invalid read of size 8
==5432==    at 0x400650: main (list2.c:22)
==5432==  Address 0x4c23188 is 0 bytes after a block of size 8 alloc'd
==5432==    at 0x4A05FDE: malloc (vg_replace_malloc.c:236)
==5432==    by 0x4005B6: main (list2.c:16)
==5432== 
0x4c23130->node {word=(nil)->[(null)], link=0x4c230e0}
0x4c230e0->node {word=0x7ff0005d1->[bar], link=0x4c23090}
0x4c23090->node {word=0x7ff0005cd->[foo], link=0x4c23040}
0x4c23040->node {word=0x7ff0005c7->[list2], link=0x37aaa0fb88}
==5432== Invalid read of size 1
==5432==    at 0x37AAA4757C: vfprintf (in /lib64/libc-2.12.so)
==5432==    by 0x37AAA4EA29: printf (in /lib64/libc-2.12.so)
==5432==    by 0x40064B: main (list2.c:23)
==5432==  Address 0xc0012000029d5 is not stack'd, malloc'd or (recently) free'd
==5432== 
==5432== 
==5432== Process terminating with default action of signal 11 (SIGSEGV)
==5432==  General Protection Fault
==5432==    at 0x37AAA4757C: vfprintf (in /lib64/libc-2.12.so)
==5432==    by 0x37AAA4EA29: printf (in /lib64/libc-2.12.so)
==5432==    by 0x40064B: main (list2.c:23)
0x37aaa0fb88->node {word=0xc0012000029d5->[==5432== 
==5432== HEAP SUMMARY:
==5432==     in use at exit: 40 bytes in 5 blocks
==5432==   total heap usage: 5 allocs, 0 frees, 40 bytes allocated
==5432== 
==5432== LEAK SUMMARY:
==5432==    definitely lost: 32 bytes in 4 blocks
==5432==    indirectly lost: 0 bytes in 0 blocks
==5432==      possibly lost: 0 bytes in 0 blocks
==5432==    still reachable: 8 bytes in 1 blocks
==5432==         suppressed: 0 bytes in 0 blocks
==5432== Rerun with --leak-check=full to see details of leaked memory
==5432== 
==5432== For counts of detected and suppressed errors, rerun with: -v
==5432== ERROR SUMMARY: 21 errors from 5 contexts (suppressed: 6 from 6)
Segmentation fault (core dumped)
bash-4.1$ gdb list2
[?1034hGNU gdb (GDB) Red Hat Enterprise Linux (7.2-50.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /afs/cats.ucsc.edu/users/a/jagwong/private/cmps012b/lab5/list2...done.
(gdb) run foo bar
Starting program: /afs/cats.ucsc.edu/users/a/jagwong/private/cmps012b/lab5/list2 foo bar
0x601090->node {word=0x7fffffffe613->[HOSTNAME=unix2.ic.ucsc.edu], link=0x601070}
0x601070->node {word=(nil)->[(null)], link=0x601050}
0x601050->node {word=0x7fffffffe60f->[bar], link=0x601030}
0x601030->node {word=0x7fffffffe60b->[foo], link=0x601010}
0x601010->node {word=0x7fffffffe5cc->[/afs/cats.ucsc.edu/users/a/jagwong/private/cmps012b/lab5/list2], link=0x37aaa0fb88}

Program received signal SIGSEGV, Segmentation fault.
0x00000037aaa4757c in vfprintf () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.47.el6_2.12.x86_64
(gdb) where
#0  0x00000037aaa4757c in vfprintf () from /lib64/libc.so.6
#1  0x00000037aaa4ea2a in printf () from /lib64/libc.so.6
#2  0x000000000040064c in main (argc=3, argv=0x7fffffffe338) at list2.c:23
(gdb) list
6	
7	typedef struct node *node_ref;
8	struct node {
9	   char *word;
10	   node_ref link;
11	};
12	
13	int main (int argc, char **argv) {
14	   node_ref head;
15	   for (int argi = 0; argi < 5; ++argi) {
(gdb) luist[K[K[K[Kist list2.c:23
18	      node->word = argv[argi];
19	      node->link = head;
20	      head = node;
21	   }
22	   for (node_ref curr = head; curr->link != NULL; curr = curr->link) {
23	      printf ("%p->node {word=%p->[%s], link=%p}\n",
24	              curr, curr->word, curr->word, curr->link);
25	   }
26	   return 9;
27	}
(gdb) print head
No symbol "head" in current context.
(gdb) up[K[Kbt
#0  0x00000037aaa4757c in vfprintf () from /lib64/libc.so.6
#1  0x00000037aaa4ea2a in printf () from /lib64/libc.so.6
#2  0x000000000040064c in main (argc=3, argv=0x7fffffffe338) at list2.c:23
(gdb) up
#1  0x00000037aaa4ea2a in printf () from /lib64/libc.so.6
(gdb) up
#2  0x000000000040064c in main (argc=3, argv=0x7fffffffe338) at list2.c:23
23	      printf ("%p->node {word=%p->[%s], link=%p}\n",
(gdb) up
Initial frame selected; you cannot go up.
(gdb) print head
$1 = (node_ref) 0x601090
(gdb) print *head
$2 = {word = 0x7fffffffe613 "HOSTNAME=unix2.ic.ucsc.edu", link = 0x601070}
(gdb) print *(head->word)
$3 = 72 'H'
(gdb) print head->link->link->link
$4 = (node_ref) 0x601030
(gdb) print *(head->link->link->link)
$5 = {word = 0x7fffffffe60b "foo", link = 0x601010}
(gdb) quit
A debugging session is active.

	Inferior 1 [process 5437] will be killed.

Quit anyway? (y or n) y
bash-4.1$ exit
exit

Script done on Tue 06 Nov 2012 10:35:51 AM PST
