Script started on Tue 06 Nov 2012 10:36:23 AM PST
[?1034hbash-4.1$ gdb list2
[?1034hGNU gdb (GDB) Red Hat Enterprise Linux (7.2-50.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /afs/cats.ucsc.edu/users/a/jagwong/private/cmps012b/lab5/list2...done.
(gdb) break main
Breakpoint 1 at 0x4005a4: file list2.c, line 15.
(gdb) run foo bar
Starting program: /afs/cats.ucsc.edu/users/a/jagwong/private/cmps012b/lab5/list2 foo bar

Breakpoint 1, main (argc=3, argv=0x7fffffffe338) at list2.c:15
15	   for (int argi = 0; argi < 5; ++argi) {
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.47.el6_2.12.x86_64
(gdb) print argc
$1 = 3
(gdb) print argv
$2 = (char **) 0x7fffffffe338
(gdb) print argv[0]
$3 = 0x7fffffffe5cc "/afs/cats.ucsc.edu/users/a/jagwong/private/cmps012b/lab5/list2"
(gdb) print argv[1]
$4 = 0x7fffffffe60b "foo"
(gdb) print argv[2]
$5 = 0x7fffffffe60f "bar"
(gdb) print argv[3]
$6 = 0x0
(gdb) print argv[4]
$7 = 0x7fffffffe613 "HOSTNAME=unix2.ic.ucsc.edu"
(gdb) print argv[5]
$8 = 0x7fffffffe62e "SELINUX_ROLE_REQUESTED="
(gdb) print argv[6]
$9 = 0x7fffffffe646 "GNUPLOT_DEFAULT_GDFONT=LiberationSans-Regular"
(gdb) quit
A debugging session is active.

	Inferior 1 [process 5820] will be killed.

Quit anyway? (y or n) y
bash-4.1$ exit
exit

Script done on Tue 06 Nov 2012 10:38:36 AM PST
