Script started on Tue 06 Nov 2012 11:48:49 AM PST
[?1034hbash-4.1$ valgrind --leak-check=full \list4 foo bar baz qux
==14750== Memcheck, a memory error detector
==14750== Copyright (C) 2002-2010, and GNU GPL'd, by Julian Seward et al.
==14750== Using Valgrind-3.6.0 and LibVEX; rerun with -h for copyright info
==14750== Command: list4 foo bar baz qux
==14750== 
0x4c23180->node {word=0x7ff0005fd->[qux], link=0x4c23130}
0x4c23130->node {word=0x7ff0005f9->[baz], link=0x4c230e0}
0x4c230e0->node {word=0x7ff0005f5->[bar], link=0x4c23090}
0x4c23090->node {word=0x7ff0005f1->[foo], link=0x4c23040}
==14750== 
==14750== HEAP SUMMARY:
==14750==     in use at exit: 0 bytes in 0 blocks
==14750==   total heap usage: 5 allocs, 5 frees, 80 bytes allocated
==14750== 
==14750== All heap blocks were freed -- no leaks are possible
==14750== 
==14750== For counts of detected and suppressed errors, rerun with: -v
==14750== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 6 from 6)
bash-4.1$ exit
exit

Script done on Tue 06 Nov 2012 11:49:07 AM PST
