Script started on Tue 06 Nov 2012 10:22:39 AM PST
[?1034hbash-4.1$ mk list1.c
+ for CSOURCE in '$*'
+ cid + list1.c
+ checksource list1.c
++ echo list1.c
++ sed 's/\.c$//'
+ EXECBIN=list1
+ gcc -g -O0 -Wall -Wextra -std=gnu99 list1.c -o list1 -lm
list1.c: In function ‘main’:
list1.c:15: warning: implicit declaration of function ‘malloc’
list1.c:15: warning: incompatible implicit declaration of built-in function ‘malloc’
list1.c:12: warning: unused parameter ‘argc’
bash-4.1$ exit
exit

Script done on Tue 06 Nov 2012 10:22:58 AM PST
